### PR TITLE
Continuous to continuously

### LINKED ISSUE #1: CONTINUOUS MATCH vs CONTINUOUSLY MATCH
I just started to play around with Graphflow. I noticed that since the SIGMOD paper, the syntax was changed from `CONTINUOUS MATCH` to `CONTINUOUSLY` MATCH.

However, some comments and error messages refer to `CONTINUOUS` instead of [`CONTINUOUSLY`](https://github.com/graphflow/graphflow/blob/172a4d762c12e77995a1c483372e7dee03adaeb7/src/main/antlr/ca/waterloo/dsg/graphflow/grammar/Graphflow.g4#L128). Using [ag](https://github.com/ggreer/the_silver_searcher), I got these results:

```$ ag "CONTINUOUS[^L]"
src/main/java/ca/waterloo/dsg/graphflow/query/executors/ContinuousMatchQueryExecutor.java
40:     * Deletes all the registered CONTINUOUS MATCH queries.

src/main/java/ca/waterloo/dsg/graphflow/query/QueryProcessor.java
61:                case CONTINUOUS_MATCH:
64:                case EXPLAIN_CONTINUOUS_MATCH:

src/main/java/ca/waterloo/dsg/graphflow/query/planner/ContinuousMatchQueryPlanner.java
48:            if (QueryOperation.EXPLAIN_CONTINUOUS_MATCH != structuredQuery.getQueryOperation()) {
59:            throw new LoadUDFException("The CONTINUOUS MATCH query could not be registered. " +

src/main/java/ca/waterloo/dsg/graphflow/query/plans/QueryPlan.java
14:            "support the explain() method. Explain is only supported for MATCH and CONTINUOUS " +
20:            "CONTINUOUS MATCH queries can be registered.");

src/main/java/ca/waterloo/dsg/graphflow/query/structuredquery/StructuredQuery.java
21:        CONTINUOUS_MATCH,
25:        EXPLAIN_CONTINUOUS_MATCH

src/main/java/ca/waterloo/dsg/graphflow/query/parser/GraphflowVisitor.java
49:        structuredQuery.setQueryOperation(QueryOperation.CONTINUOUS_MATCH);
76:        structuredQuery.setQueryOperation(QueryOperation.EXPLAIN_CONTINUOUS_MATCH);

src/main/java/ca/waterloo/dsg/graphflow/query/output/MatchQueryOutput.java
10: * Represents the output of a MATCH or CONTINUOUS MATCH query in the absence of aggregations.

src/test/java/ca/waterloo/dsg/graphflow/query/operator/UDFSinkTest.java
61:        // Test the output of the registered CONTINUOUS MATCH query.

src/test/java/ca/waterloo/dsg/graphflow/query/executors/ContinuousMatchQueryExecutorTest.java
43:     * Tests the execution of a triangle CONTINUOUS MATCH query.
47:        // Register a triangle CONTINUOUS MATCH query.
73:        // Execute the registered CONTINUOUS MATCH query.
81:        // Test the output of the registered CONTINUOUS MATCH query.
```

There are also instances of `continuousMatch` and `ContinuousMatch`, but I'm less sure about renaming these, so I created a separate commit for these in the upcoming PR.

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #1

I turned on the Travis build for my fork of the repository: https://travis-ci.org/szarnyasg/graphflow

### CODE REVIEW

**Comment by queryproc** [comment]
We used to make the distinction on continuous match queries as a noun and continuously match as a verb within a query. I was slightly on the fence on this one but after going over the changes I find it is better to just be consistent with continuously match everywhere.

Thank you for the PR! Hopefully many more will come.

**Comment by queryproc** [comment]
We used to make the distinction on continuous match queries as a noun and continuously match as a verb within a query. I was slightly on the fence on this one but after going over the changes I find it is better to just be consistent with continuously match everywhere. We will wait for Sid's opinion on this one.

Thank you for the PR! Hopefully many more will come.

**Comment by szarnyasg** [comment]
@queryproc I started to implement Graphflow with a Master's student for the [Train Benchmark](https://github.com/FTSRG/trainbenchmark), a benchmark project that my research group has been developing since 2011 ([paper](https://link.springer.com/article/10.1007/s10270-016-0571-8)). If this is interesting for you, we should get in touch on [LinkedIn](https://www.linkedin.com/in/szarnyasg) / Skype / email.

**Comment by queryproc** [comment]
@szarnyasg I will reach out by e-mail and CC our research group and we can take it from there.

**Comment by szarnyasg** [comment]
Great, thanks. We are also developing an incremental openCypher engine, [ingraph](http://docs.inf.mit.bme.hu/ingraph/), so it'll be interesting to discuss potential collaborations.

**Comment by siddharthasahu** [comment]
Hi @szarnyasg,

Thank you very much for working on this.

I'm not sure if this is the right way to go though. We changed Continuous to Continuously to make it a verb when users type in a query. This made it consistent with other commands like MATCH and CREATE, which are read as verbs. On the other hand, in the code, the class and variable names are nouns, which makes  EXPLAIN_CONTINUOUSLY_MATCH and ContinuouslyMatchQueryPlanner awkward to read.

I don't feel very strongly about this though. @queryproc and @szarnyasg please think about the above point and if does not matter too much, lets merge this!

Thanks

**Comment by queryproc** [comment]
@szarnyasg @siddharthasahu 
I kind of agree with Sid on the naming of classes becoming awkward due to the verb/noun confusion at times. I think it is better to revisit especially once we have the continuous shortest path queries on master.
We can then decide the naming in the code as that naming would need to be consistent for both.

**Comment by szarnyasg** [comment]
I guess Phil Karlton was right that [naming things](http://hilton.org.uk/blog/why-naming-things-is-hard) is hard :-). I updated the PR, which now only considers comments with mentioning "CONTINUOUS[LY] MATCH".

**Pull request merged**
